### ISSUE TITLE
Conflicting Id's during partial page refresh

### ISSUE THREAD

**Issue by peterdotjs** [raptorjs/marko-widgets#16]
Is there a recommended way to generate unique id's for marko widgets?

The problem we are facing is when we have a partial page refresh. On the initial page load the IDs are unique. However if we partially refresh a part of the page, there will be collisions with the IDs. This is with the auto-generated IDs. 

We thought of using a server side timestamp to generate the unique identifier with some namespace but even then there were collisions. 

Any suggestions?

**Comment by patrick-steele-idem** [comment]
Good question. This has come up before and we made some code changes to support this use case. The problem is that the server is not keeping any state and the unique IDs reset back to `0` reset for each request. As a workaround, we allow the application code to provide a "widget ID prefix" which is just some string that is prefixed to the auto generated ID and this prefix can be used to keep widget IDs unique across requests (assuming the application code provides an appropriate prefix).

The widget ID prefix should be provided as part of the rendering "global" object as shown in the following sample code:

```javascript
template.render({
        $global: {
            widgetIdPrefix: 'w' + Math.random()
        }
    },
    function(err, html) {

    });
```

Here is the related code that is used to generate unique IDs on the server: [lib/uniqueId.js](lib/uniqueId.js)

Does that solve your problem?

**Comment by peterdotjs** [comment]
Yeah that should work. We'll give it a try.

Correcting the link you listed: 
https://github.com/raptorjs/marko-widgets/blob/master/lib/uniqueId.js

**Comment by patrick-steele-idem** [comment]
Please update this Github issue when verified.

I have updated the link. Thanks.

**Comment by patrick-steele-idem** [comment]
ping. Did this solution work for you?

**Comment by peterdotjs** [comment]
Sorry, I didn't close this sooner. The suggested fix works great.
