### ISSUE TITLE
v4.0: Rendering/Rerendering functions not called when filename is different from "index.js"

### ISSUE THREAD

**Issue by schetnikovich** [raptorjs/marko-widgets#35]
To simplify description of this issue, I've created a minimal project: https://github.com/schetnikovich/marko-widgets-question

This project consists of two identical widgets (`good-widget` and `bad-widget`) with the only difference in widget's file name:

```js
src/good-widget/index.js
src/bad-widget/widget.js
```

When using `bad-widget`, function `getTemplateData()` seems not called. For `good-widget` everything is okay. Am I missing something?

**Comment by BryceEWatson** [comment]
I've noticed that the output file, page-home/template.marko.js, creates the two widgets in different ways.. It looks like good widget is treated as a marko-widget, while bad widget is treated as a marko template. Is there some logic that assumes index.js is a widget, while widget.js is a template? Or maybe this is a red herring.

good_widget = renderer(require("..\good-widget")),
_bad_widget_template_marko = __helpers.l(require.resolve("..\bad-widget\template.marko"));

**Comment by philidem** [comment]
As @BryceEWatson mentioned, `bad-widget` was being rendered simply as a template since there was no `index.js` with a renderer. If `bad-widget` is rendered on the client-side then you'll see that the `getTemplateData` function inside `widget.js` will be called.

So, if you want to utilize the same code on the client and server then use `index.js`. If a component can only be rendered on server-side then you can use `renderer.js` (whic is more of a `marko` concept).

Closing this issue but feel free to add additional comments to discuss. Also, let me know if you have any questions about my modifications in https://github.com/schetnikovich/marko-widgets-question/pull/1

**Comment by tindli** [comment]
Instead of having the behaviour depend on the name of the file wouldn't it be more intuitive if there would be a property in the component that defines where to use it?
Then we would only need one filename thus the path to w-bind could always be omitted (and not having it to to do a lookup for widget.js or index.js since there would only be one...)

Am I missing something?
