### ISSUE TITLE
Using w-bind without introducing additional markup

### ISSUE THREAD

**Issue by yomed** [raptorjs/marko-widgets#45]
The main use case for w-bind goes something like this:
`<div w-bind>`
    `Hello ${data.name}!`
`</div>`

However, there are certain cases where there isn't a parent element that can take the w-bind. For example, consider a widget that manages the pagination links in the head:
`<link rel="prev" href="http://www.example.com/article?page=1" />`
`<link rel="next" href="http://www.example.com/article?page=3" />`

You can't introduce any parent markup to bind, because markup like divs aren't allowed in the head. Additionally, placing a w-bind on just one of the links has some strange results. Theoretically you could put w-bind directly on `<head>` and create a head widget instead, but it seems like that shouldn't be necessary.

**Comment by patrick-steele-idem** [comment]
One of the central requirements of a widget is that it be bound to a DOM element. We can't change that because that is how we manage creating and destroying widgets. You might want to consider binding a widget to a HTML element with no display such as `<noscript>`:

```xml
<noscript w-bind/>
```

Alternatively, you my want to roll up this "behavior" into a top-level widget in your app.

Please let me know if either of those solutions work for you so that we can know if this issue can be closed or kept open.

**Comment by yomed** [comment]
Yeah, I think those are both reasonable solutions. And given that parent DOM elements are baked into the project, seems ok to close this.
